import React from 'react';
import { Bot, CheckCircle2, FileText, Globe2, Headphones, LockKeyhole, Mic, Sparkles, Workflow } from 'lucide-react';
import { Header } from '../components/landing/Header';
import { BrandLogo } from '../components/landing/BrandLogo';
import { Button } from '../components/common/Button';
import { SkipLink } from '../components/accessibility/SkipLink';

interface Props { onNavigate: (path: string) => void; }
const cards = 'rounded-2xl border border-slate-200 bg-white p-5 shadow-card-soft';

function Shell({ onNavigate, title, intro, children }: Props & { title: string; intro: string; children: React.ReactNode }) {
  return <div className="min-h-screen bg-slate-50 text-slate-900"><SkipLink /><Header onNavigate={onNavigate} /><main id="main-content" tabIndex={-1} className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16 focus:outline-none"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-wider text-brand-700">AccessAI</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">{title}</h1><p className="mt-4 text-base leading-7 text-slate-600">{intro}</p></div><div className="mt-10">{children}</div></main><footer className="border-t border-slate-200 bg-white py-6"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 text-xs text-slate-500 sm:px-6"><BrandLogo size="sm" /><span>AccessAI</span></div></footer></div>;
}

const FeatureCard = ({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) => <article className={cards}><div className="mb-4 inline-flex rounded-xl bg-brand-50 p-2.5 text-brand-700">{icon}</div><h2 className="text-lg font-bold">{title}</h2><div className="mt-2 text-sm leading-6 text-slate-600">{children}</div></article>;

export const FeaturesPage: React.FC<Props> = ({ onNavigate }) => <Shell onNavigate={onNavigate} title="Accessibility support for real forms" intro="AccessAI focuses on the completed MVP features that help people understand and complete complex documents with more confidence."><section className="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><FeatureCard icon={<Bot />} title="AI document understanding">Upload a complex PDF or supported image. Gemini analyzes it, and AccessAI extracts only fields supported by evidence in the source document.</FeatureCard><FeatureCard icon={<Workflow />} title="Guided accessible forms">Complete clear sections with plain-language explanations, required-field validation, and saved progress to resume later.</FeatureCard><FeatureCard icon={<Mic />} title="Voice accessibility">Use speech input and listen to field instructions in English, Hindi, Telugu, or Kannada. Browser speech support and microphone access can vary.</FeatureCard><FeatureCard icon={<Globe2 />} title="Multilingual support">Choose English, Hindi, Telugu, or Kannada. Gemini translates field instructions used by Listen when available.</FeatureCard><FeatureCard icon={<FileText />} title="Review + PDF">Review answers before finalization, generate a completed PDF, and download it through the protected document flow.</FeatureCard><FeatureCard icon={<Sparkles />} title="Browser automation">Puppeteer opens a separate browser and fills only high-confidence supported matches. Ambiguous fields need manual review; it does not bypass CAPTCHAs or submit sensitive forms automatically.</FeatureCard><FeatureCard icon={<LockKeyhole />} title="Privacy + security">Access uses authenticated or guest ownership checks, HTTP-only cookies, and a server-side Gemini API key. External-site credentials are not stored.</FeatureCard></section></Shell>;

export const HowItWorksPage: React.FC<Props> = ({ onNavigate }) => { const steps = ['Upload your document', 'AI understands the document', 'AccessAI creates a guided form', 'Complete it with text or voice', 'Review your answers', 'Download the completed PDF or automate a supported web form']; return <Shell onNavigate={onNavigate} title="How AccessAI works" intro="From document to guided completion in a few clear steps."><ol className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{steps.map((step, index) => <li key={step} className={cards}><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-brand-700 text-sm font-bold text-white">{index + 1}</span><h2 className="mt-4 font-bold">{step}</h2></li>)}</ol><div className="mt-10"><Button size="lg" onClick={() => onNavigate('/upload')}>Get Started</Button></div></Shell>; };

export const AboutPage: React.FC<Props> = ({ onNavigate }) => <Shell onNavigate={onNavigate} title="Turn complex forms into simple, accessible conversations." intro="AccessAI combines AI-powered document understanding with accessibility-first guided completion."><div className="grid gap-5 md:grid-cols-2"><section className={cards}><h2 className="text-lg font-bold">Our mission</h2><p className="mt-3 text-sm leading-6 text-slate-600">Complex forms should not be a barrier. AccessAI helps people work through documents with plain language, multilingual assistance, voice support, and clear review steps.</p></section><section className={cards}><h2 className="text-lg font-bold">Designed with care</h2><p className="mt-3 text-sm leading-6 text-slate-600">The product keeps API keys server-side, uses ownership checks, supports guided completion, and offers conservative browser automation with manual review.</p></section></div></Shell>;

export const SecurityPage: React.FC<Props> = ({ onNavigate }) => <Shell onNavigate={onNavigate} title="Privacy and security by design" intro="AccessAI is designed to keep document handling and external-form assistance within clear safety boundaries."><div className="grid gap-4 md:grid-cols-2">{['Authenticated and guest access use the existing ownership checks.', 'Refresh and guest session cookies are HTTP-only.', 'The Gemini API key stays server-side and is never exposed to the browser.', 'Documents use the configured temporary retention and cleanup process.', 'Puppeteer does not store external-site credentials, bypass CAPTCHAs, or automatically submit sensitive forms.'].map((item) => <div key={item} className={cards}><CheckCircle2 className="h-5 w-5 text-emerald-700" /><p className="mt-3 text-sm leading-6 text-slate-700">{item}</p></div>)}</div></Shell>;

export const HelpPage: React.FC<Props> = ({ onNavigate }) => { const faq = [['What file types are supported?', 'PDF, PNG, and JPEG files are supported by the upload service.'], ['Can I use AccessAI without an account?', 'Yes. You can start a guest session; document access remains limited to that guest session.'], ['Why is voice input not working?', 'Allow microphone access in your browser. Speech recognition depends on Web Speech API support and may vary by browser.'], ['Why did a field not appear?', 'AccessAI intentionally avoids guessing fields that are not reliably supported by the source document.'], ['Why does browser automation need review?', 'Only strong field matches are filled. You review the separate browser window and submit the form yourself.'], ['Does AccessAI store my Gemini API key?', 'No. The API key is kept server-side and is not exposed to your browser.'], ['Can Puppeteer bypass CAPTCHA or submit sensitive forms?', 'No. It does not bypass CAPTCHA, and it never automatically submits sensitive forms.']]; return <Shell onNavigate={onNavigate} title="Help & support" intro="Simple guidance for each part of the AccessAI journey."><section className="grid gap-4 md:grid-cols-2"><FeatureCard icon={<Headphones />} title="Getting started">Upload a PDF or image, wait for the guided form, then enter answers by text or voice. Use Listen for translated field instructions, review your answers, and generate your completed PDF. Browser automation opens a separate window for safe manual review.</FeatureCard><section className={cards}><h2 className="text-lg font-bold">Need help?</h2><p className="mt-2 text-sm leading-6 text-slate-600">Report an issue to the project team with a copyable summary. No message is sent automatically.</p><Button className="mt-4" variant="outline" onClick={() => navigator.clipboard?.writeText(`AccessAI issue report\nPage: ${window.location.pathname}\nBrowser: ${navigator.userAgent}`)}>Copy diagnostic summary</Button></section></section><section className="mt-8"><h2 className="text-xl font-bold">Frequently asked questions</h2><div className="mt-4 space-y-3">{faq.map(([question, answer]) => <details key={question} className={cards}><summary className="cursor-pointer font-semibold text-slate-800">{question}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{answer}</p></details>)}</div></section></Shell>; };
